"""Unit tests for Hexaqual check and sanity CLI commands."""

from __future__ import annotations

from unittest.mock import patch

import typer
from typer.testing import CliRunner

from hexaqual.cli.check import register_check_commands

runner = CliRunner()


def test_register_check_commands() -> None:
    """Test registering check commands on a fresh Typer app."""
    test_app = typer.Typer()
    register_check_commands(test_app)

    with patch("hexaqual.cli.check._execute_sanity_pipeline") as mock_run:
        res = runner.invoke(test_app, ["check", "--skip-tests"])
        assert res.exit_code == 0
        assert mock_run.called


def test_check_dynamic_skip_options() -> None:
    """Test dynamic --skip-* options and aliases generated by WorkflowCliBinder."""
    test_app = typer.Typer()
    register_check_commands(test_app)

    with patch("hexaqual.cli.check._execute_sanity_pipeline") as mock_run:
        res = runner.invoke(test_app, ["check", "--skip-ruff", "--skip-ty", "--skip-tests"])
        assert res.exit_code == 0
        assert mock_run.called
        call_kwargs = mock_run.call_args[1]
        assert "pytest" in call_kwargs["skip_steps"]
        assert "typecheck" in call_kwargs["skip_steps"]
        assert "lint" in call_kwargs["skip_steps"]


def test_sanity_alias_command() -> None:
    """Test sanity alias forwards to check command."""
    test_app = typer.Typer()
    register_check_commands(test_app)

    with patch("hexaqual.cli.check._execute_sanity_pipeline") as mock_run:
        res = runner.invoke(test_app, ["sanity", "--skip-tests"])
        assert res.exit_code == 0
        assert mock_run.called


def test_check_failure_exit_code() -> None:
    """Test non-zero exit code on sanity check failure."""
    test_app = typer.Typer()
    register_check_commands(test_app)

    with patch("hexaqual.cli.check._execute_sanity_pipeline", side_effect=typer.Exit(code=1)):
        res = runner.invoke(test_app, ["check", "--skip-tests"])
        assert res.exit_code == 1


def test_complexity_command_success() -> None:
    """Test complexity command invokes runner successfully."""
    test_app = typer.Typer()
    register_check_commands(test_app)

    from hexaqual.domain.governance import CheckResult, CheckStatus

    mock_res = CheckResult(
        check_name="Cognitive Complexity",
        target_name="workspace",
        status=CheckStatus.PASS,
        duration=0.1,
    )
    with patch(
        "hexaqual.adapters.runners.subprocess_runner.SubprocessToolRunnerAdapter.run_complexipy",
        return_value=mock_res,
    ) as mock_run:
        res = runner.invoke(test_app, ["complexity", "-mx", "20", "-p", "core"])
        assert res.exit_code == 0
        assert mock_run.called
        assert mock_run.call_args[1]["max_complexity"] == 20


def test_complexity_command_failure() -> None:
    """Test complexity command exits non-zero on violations."""
    test_app = typer.Typer()
    register_check_commands(test_app)

    from hexaqual.domain.governance import CheckResult, CheckStatus

    mock_res = CheckResult(
        check_name="Cognitive Complexity",
        target_name="workspace",
        status=CheckStatus.FAIL,
        duration=0.1,
        error_output="Violation found",
    )
    with patch(
        "hexaqual.adapters.runners.subprocess_runner.SubprocessToolRunnerAdapter.run_complexipy",
        return_value=mock_res,
    ):
        res = runner.invoke(test_app, ["complexity"])
        assert res.exit_code == 1
