"""Workspace infrastructure module providing workspace discovery.

Notes/Architectural Intent:
    Delegates to adapters.workspace, providing infrastructure-level access to
    workspace discovery and path resolution.
"""

from hexaqual.adapters.workspace import (
    HEX_LAYERS,
    LAYER_RESTRICTIONS,
    PACKAGES_DIR,
    VALID_EXAMPLES,
    VALID_PACKAGES,
    HexastackScriptArgumentParser,
    LocalWorkspaceAdapter,
    check_tool_availability,
    ensure_tool_installed,
    get_canonical_scripts,
    get_downstream_dependents,
    get_example_directories,
    get_example_directory,
    get_package_dependencies,
    get_package_directories,
    get_package_directory,
    get_package_module_dir,
    get_packages_directory,
    get_present_layers,
    get_repo_root,
    get_valid_example_names,
    get_valid_package_names,
    get_workspace_dependency_graph,
    get_workspace_scripts,
    group_scripts_by_entrypoint,
    has_examples,
    is_multipackage_workspace,
    resolve_affected_packages,
    resolve_target_python_files,
)

__all__ = [
    "check_tool_availability",
    "ensure_tool_installed",
    "get_canonical_scripts",
    "get_downstream_dependents",
    "get_example_directories",
    "get_example_directory",
    "get_package_dependencies",
    "get_package_directories",
    "get_package_directory",
    "get_package_module_dir",
    "get_packages_directory",
    "get_present_layers",
    "get_repo_root",
    "get_valid_example_names",
    "get_valid_package_names",
    "get_workspace_dependency_graph",
    "get_workspace_scripts",
    "group_scripts_by_entrypoint",
    "has_examples",
    "HEX_LAYERS",
    "HexastackScriptArgumentParser",
    "is_multipackage_workspace",
    "LAYER_RESTRICTIONS",
    "LocalWorkspaceAdapter",
    "PACKAGES_DIR",
    "resolve_affected_packages",
    "resolve_target_python_files",
    "VALID_EXAMPLES",
    "VALID_PACKAGES",
]
